global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FitnessPro Backend API
  - job_name: 'fitness-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    scrape_interval: 30s

  # Nginx Reverse Proxy
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']
    scrape_interval: 30s

  # Node.js Application Metrics
  - job_name: 'node-app-metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/metrics/nodejs'
    scrape_interval: 30s

  # Custom Business Metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/metrics/business'
    scrape_interval: 60s

  # Health Checks
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://your-domain.com/api/health
        - https://your-domain.com/api/health/db
        - https://your-domain.com/api/health/redis
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

# Remote write for long-term storage (optional)
remote_write:
  - url: "https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push"
    basic_auth:
      username: "your-grafana-username"
      password: "your-grafana-api-key"
