[build]
  builder = "NIXPACKS"
  buildCommand = "bun install && bunx prisma generate && bun run build"

[deploy]
  startCommand = "bunx prisma migrate deploy && bun run db:seed && bun run start:prod"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 100
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[env]
  NODE_ENV = "production"
  PORT = "8000"
  DEFAULT_CURRENCY = "UAH"

  # LiqPay Configuration (Sandbox)
  LIQPAY_PUBLIC_KEY = "sandbox_i74424594321"
  LIQPAY_PRIVATE_KEY = "sandbox_demoPrivateKey2024"
  LIQPAY_SANDBOX = "true"

  # Frontend URL (update after Netlify deployment)
  FRONTEND_URL = "https://fitnesspro-app.netlify.app"
  CORS_ORIGIN = "https://fitnesspro-app.netlify.app"
