[build]
  builder = "NIXPACKS"
  buildCommand = "bun install && bunx prisma generate && bun run build"

[deploy]
  startCommand = "bunx prisma migrate deploy && bun run start:prod"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 100
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[env]
  NODE_ENV = "production"
  PORT = "8000"

# Database service
[[services]]
  name = "postgres"
  source = "postgres:15"

  [services.env]
    POSTGRES_DB = "fitness_pro_production"
    POSTGRES_USER = "fitness_user"

# Redis service
[[services]]
  name = "redis"
  source = "redis:7"

# Backend service
[[services]]
  name = "backend"
  source = "."

  [services.env]
    DATABASE_URL = "${{postgres.DATABASE_URL}}"
    REDIS_URL = "${{redis.REDIS_URL}}"

  [[services.volumeMounts]]
    mountPath = "/app/uploads"
    volumeId = "uploads"

# Volume for file uploads
[[volumes]]
  id = "uploads"
  name = "uploads-volume"
  size = "10GB"

# Custom domains
[[domains]]
  domain = "api.your-domain.com"
  service = "backend"

# Monitoring
[monitoring]
  enabled = true

  [[monitoring.checks]]
    name = "health-check"
    url = "/api/health"
    interval = "30s"
    timeout = "10s"

  [[monitoring.checks]]
    name = "database-check"
    url = "/api/health/db"
    interval = "60s"
    timeout = "15s"
